name: Crypto Live — September Baseline (15m DRY-RUN)

on:
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: "ON = simulate, OFF = live trading"
        required: false
        default: "ON"
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes

permissions:
  contents: read
  actions: read
  id-token: write

concurrency:
  group: crypto-live
  cancel-in-progress: false

env:
  EXCHANGE: "kraken"
  STATE_DIR: ".state"
  POSITIONS_JSON: ".state/positions.json"
  KPI_CSV: ".state/kpi_history.csv"
  GUARD_FILE: ".state/guard.yaml"

jobs:
  run:
    name: CryptoBot 15m Run (DRY-RUN)
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [[ -f requirements.txt ]]; then
            pip install -r requirements.txt
          else
            pip install ccxt pyyaml pandas
          fi

      - name: Ensure .state and guard.yaml
        shell: bash
        run: |
          mkdir -p .state
          if [[ ! -f "${GUARD_FILE}" ]]; then
            cat > "${GUARD_FILE}" <<'YAML'
            run_switch: "ON"
            dry_run: "ON"
            sizing:
              min_buy_usd: 10
              min_sell_usd: 10
              reserve_cash_pct: 5
              max_positions: 3
              max_buys_per_run: 2
            universe:
              top_k: 25
            rotation:
              when_full: true
              when_cash_short: true
            dust:
              min_usd: 2
              skip_stables: true
            sell:
              take_profit_pct: 0.02      # TAKE_PROFIT
              stop_loss_pct: 0.03        # STOP_LOSS
              trail_arm_pct: 0.03        # TRAIL arm
              trail_giveback_pct: 0.015  # TRAIL giveback
            YAML
          fi
          [[ -f "${POSITIONS_JSON}" ]] || echo "{}" > "${POSITIONS_JSON}"
          [[ -f "${KPI_CSV}" ]] || echo "timestamp,base,bal_usd,pnl_day_usd,buys,sells,open_positions" > "${KPI_CSV}"

      - name: Run CryptoBot (Dry-run safe)
        env:
          EXCHANGE: ${{ env.EXCHANGE }}
          STATE_DIR: ${{ env.STATE_DIR }}
          POSITIONS_JSON: ${{ env.POSITIONS_JSON }}
          KPI_CSV: ${{ env.KPI_CSV }}
          GUARD_FILE: ${{ env.GUARD_FILE }}
          DRY_RUN: ${{ inputs.DRY_RUN }}
        run: |
          echo "Starting CryptoBot (Exchange=${EXCHANGE}, DRY_RUN=${DRY_RUN})"
          python main.py --mode crypto --exchange "${EXCHANGE}" --dryrun "${DRY_RUN}"

      - name: Upload .state artifact
        uses: actions/upload-artifact@v4
        with:
          name: state-after-run
          path: .state/**
          retention-days: 7

      - name: Summary
        shell: bash
        run: |
          echo "### ✅ CryptoBot September Baseline run complete" >> $GITHUB_STEP_SUMMARY
          echo "- Exchange: ${EXCHANGE}" >> $GITHUB_STEP_SUMMARY
          echo "- DRY_RUN: ${DRY_RUN}" >> $GITHUB_STEP_SUMMARY
          echo "- Schedule: every 15 minutes" >> $GITHUB_STEP_SUMMARY
