name: Cron Poke (5m)

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show UTC time
        run: |
          echo "Hi from cron"
          date -u
