name: Crypto Live (Every 15 min)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes

jobs:
  live:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      # --- Safety & knobs ---
      DRY_RUN: "false"                # "true" for testing, "false" for live
      TRADE_AMOUNT: "10"
      MAX_TRADES_PER_RUN: "2"
      TP: "0.015"                     # 1.5% take-profit marker (logic reserved for future)
      SL: "0.03"                      # 3.0% stop-loss marker (logic reserved for future)
      TRAIL: "0.02"                   # 2.0% trailing buffer (logic reserved for future)
      DROP_PCT: "0.005"                # buy if price is >=1% below SMA10
      MIN_NOTIONAL_BUFFER: "1.0"      # cushion added to required-per-run math
      TIMEFRAME: "5m"
      SMA_LEN: "10"
      SYMBOLS: "DOGE/USD,XRP/USD,ADA/USD,ETH/USD,BTC/USD"

      # ccxt/kraken envs from Actions secrets
      KRAKEN_API_KEY: ${{ secrets.KRAKEN_API_KEY }}
      KRAKEN_SECRET:  ${{ secrets.KRAKEN_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ccxt

      - name: Run trader
        run: |
          set -e
          python --version
          python main.py
