name: Crypto Live (Debug)

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    concurrency:
      group: crypto-live-debug
      cancel-in-progress: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Crypto Live DEBUG (raise warnings as errors)
        env:
          # Force LIVE
          TRADE_MODE: "live"
          DRY_RUN: "false"

          # Limit to crypto only
          MARKET: "crypto"
          EQUITY_BROKER: "none"
          SYMBOLS: "BTC-USD"

          # Exchange selection
          EXCHANGE: "kraken"
          CCXT_EXCHANGE: "kraken"

          # API creds
          CRYPTO_API_KEY:    ${{ secrets.KRAKEN_API_KEY }}
          CRYPTO_API_SECRET: ${{ secrets.KRAKEN_API_SECRET }}
          CCXT_API_KEY:      ${{ secrets.KRAKEN_API_KEY }}
          CCXT_API_SECRET:   ${{ secrets.KRAKEN_API_SECRET }}
          KRAKEN_API_KEY:    ${{ secrets.KRAKEN_API_KEY }}
          KRAKEN_API_SECRET: ${{ secrets.KRAKEN_API_SECRET }}

          # Turn pandas warnings into errors to get a traceback
          PYTHONWARNINGS: "error"

          # Optional: make your app noisier
          LOG_LEVEL: "DEBUG"
        run: |
          set -euxo pipefail
          python -V
          # Also pass -W error via CLI to be extra sure
          python -W error main.py \
            --market crypto \
            --exchange kraken \
            --strategy cautious \
            --cap_per_trade 10 \
            --cap_daily 15 \
            --dry_run false
