name: Crypto Live (Every 15 min)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

concurrency:
  group: crypto-live
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"

  # --- Stop-loss knobs ---
  STOP_LOSS_PCT: "2.0"
  STOP_LOSS_USE_LIMIT: "true"
  STOP_LOSS_LIMIT_OFFSET_BP: "10"

  # --- Live knobs ---
  DRY_RUN: "false"
  SKIP_BALANCE_PING: "false"
  TRADE_AMOUNT: "20"
  AUTO_TOP_UP_MIN: "true"
  MIN_ORDER_BUFFER_USD: "0.50"
  MIN_NOTIONAL_FLOOR_USD: "20"
  DAILY_CAP: "50"
  DAILY_CAP_TZ: "America/Los_Angeles"

  # --- Selection / universe ---
  DROP_PCT: "1.5"
  UNIVERSE_SIZE: "200"
  PREFERRED_QUOTES: "USD"
  MIN_DOLLAR_VOL_24H: "200000"
  MIN_PRICE: "0.01"
  EXCLUDE: "U/USD"
  WHITELIST: ""

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Echo live env
        run: |
          echo "DRY_RUN=${DRY_RUN}"
          echo "SKIP_BALANCE_PING=${SKIP_BALANCE_PING}"
          echo "TRADE_AMOUNT=${TRADE_AMOUNT}"
          echo "AUTO_TOP_UP_MIN=${AUTO_TOP_UP_MIN}"
          echo "MIN_ORDER_BUFFER_USD=${MIN_ORDER_BUFFER_USD}"
          echo "DAILY_CAP=${DAILY_CAP}"
          echo "DAILY_CAP_TZ=${DAILY_CAP_TZ}"
          echo "DROP_PCT=${DROP_PCT}"
          echo "UNIVERSE_SIZE=${UNIVERSE_SIZE}"
          echo "PREFERRED_QUOTES=${PREFERRED_QUOTES}"
          echo "MIN_DOLLAR_VOL_24H=${MIN_DOLLAR_VOL_24H}"
          echo "MIN_PRICE=${MIN_PRICE}"
          echo "EXCLUDE=${EXCLUDE}"
          echo "WHITELIST=${WHITELIST}"

      - name: Run trader
        env:
          KRAKEN_API_KEY: ${{ secrets.KRAKEN_API_KEY }}
          KRAKEN_SECRET: ${{ secrets.KRAKEN_API_SECRET }}
        run: |
          python -V
          python main.py
