name: Crypto Live — Overnight (15m DRY-RUN by default)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: "OFF to trade live; ON for dry run"
        type: choice
        required: true
        default: "ON"
        options: ["ON", "OFF"]
      RUN_SWITCH:
        description: "Global on/off (ON runs, OFF skips trading logic)"
        type: choice
        required: true
        default: "ON"
        options: ["ON", "OFF"]
      ADVANCED_JSON:
        description: "Optional advanced config JSON (sizing, caps, etc.)"
        required: false
        type: string
      PROTECT_JSON:
        description: "Optional guard/protect JSON (TP/SL/TSL, sell rules, etc.)"
        required: false
        type: string

concurrency:
  group: crypto-live-overnight
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  live:
    runs-on: ubuntu-latest

    env:
      DRY_RUN: ${{ inputs.DRY_RUN || 'ON' }}
      RUN_SWITCH: ${{ inputs.RUN_SWITCH || 'ON' }}
      MIN_BUY_USD:            ${{ vars.MIN_BUY_USD || '10' }}
      MAX_POSITIONS:          ${{ vars.MAX_POSITIONS || '3' }}
      MAX_BUYS_PER_RUN:       ${{ vars.MAX_BUYS_PER_RUN || '1' }}
      UNIVERSE_TOP_K:         ${{ vars.UNIVERSE_TOP_K || '25' }}
      RESERVE_CASH_PCT:       ${{ vars.RESERVE_CASH_PCT || '5' }}
      ROTATE_WHEN_FULL:       ${{ vars.ROTATE_WHEN_FULL || 'true' }}
      ROTATE_WHEN_CASH_SHORT: ${{ vars.ROTATE_WHEN_CASH_SHORT || 'true' }}
      MIN_SELL_USD:           ${{ vars.MIN_SELL_USD || '10' }}
      DUST_MIN_USD:           ${{ vars.DUST_MIN_USD || '2' }}
      DUST_SKIP_STABLES:      ${{ vars.DUST_SKIP_STABLES || 'true' }}
      ADVANCED_JSON: ${{ inputs.ADVANCED_JSON || '' }}
      PROTECT_JSON:  ${{ inputs.PROTECT_JSON  || '' }}
      STATE_DIR: ".state"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure .state/ exists + sentinel
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$STATE_DIR"
          echo "created: $(date -Iseconds)" > "$STATE_DIR/ARTIFACT_SENTINEL.txt"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (requirements.txt if present, else minimal)
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [[ -f requirements.txt ]]; then
            pip install -r requirements.txt
          else
            pip install pyyaml matplotlib pandas requests
          fi

      - name: Run trading bot
        id: run_bot
        shell: bash
        env:
          KRAKEN_API_KEY:    ${{ secrets.KRAKEN_API_KEY }}
          KRAKEN_API_SECRET: ${{ secrets.KRAKEN_API_SECRET }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          set -euo pipefail
          echo "DRY_RUN=${DRY_RUN}"
          echo "RUN_SWITCH=${RUN_SWITCH}"

          if [[ "${RUN_SWITCH}" != "ON" ]]; then
            echo "RUN_SWITCH is OFF → skip trading logic."
            echo "skip" > "${STATE_DIR}/run_skipped.txt"
            exit 0
          fi

          {
            echo "=== Crypto Live Run ==="
            echo "started: $(date -Iseconds)"
            echo "DRY_RUN=${DRY_RUN}"
            echo "ADVANCED_JSON length: ${#ADVANCED_JSON}"
            echo "PROTECT_JSON length: ${#PROTECT_JSON}"
          } | tee "${STATE_DIR}/run_header.txt"

          python main.py

          echo "completed: $(date -Iseconds)" | tee -a "${STATE_DIR}/run_header.txt"

      - name: Generate KPI chart (optional)
        if: always() && hashFiles('tools/make_kpi_chart.py') != ''
        shell: bash
        run: |
          set -euo pipefail
          python tools/make_kpi_chart.py || echo "KPI chart generation skipped/failed."

      # -------- Fix: prove files exist and upload via absolute path ----------
      - name: Debug: list .state before upload
        if: always()
        shell: bash
        run: |
          set -euxo pipefail
          echo "Workspace: ${GITHUB_WORKSPACE}"
          ls -la
          if [[ -d ".state" ]]; then
            echo "Contents of .state:"
            find .state -maxdepth 3 -type f -printf "%p (%s bytes)\n" || true
          else
            echo ".state directory is missing."
          fi

      - name: Upload .state artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: state-${{ github.run_id }}
          # Use absolute workspace path to avoid any glob/relpath edge cases
          path: ${{ github.workspace }}/.state
          if-no-files-found: warn
          retention-days: 7
          compression-level: 6

      - name: Upload run report (optional)
        if: always() && hashFiles('.state/run_header.txt') != ''
        uses: actions/upload-artifact@v4
        with:
          name: run-report-${{ github.run_id }}
          path: .state/run_header.txt
          if-no-files-found: warn
          retention-days: 7

      - name: (Optional) Send Slack summary
        if: ${{ false }}
        shell: bash
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          set -euo pipefail
          test -n "${SLACK_WEBHOOK_URL:-}" || { echo "No webhook; skipping."; exit 0; }
          msg="*Crypto Live — Overnight* finished run ${{ github.run_number }} (DRY_RUN=${DRY_RUN})"
          payload=$(jq -n --arg text "$msg" '{text:$text}')
          curl -sS -X POST -H 'Content-type: application/json' --data "${payload}" "${SLACK_WEBHOOK_URL}" || true
