name: Crypto Live (Cautious)

on:
  workflow_dispatch:

env:
  # Python
  PYTHON_VERSION: "3.11"

  # --- Stop-loss knobs ---
  STOP_LOSS_PCT: "2.0"               # % below filled buy price (e.g., 2.0 = 2%)
  STOP_LOSS_USE_LIMIT: "true"        # true = stop-loss-LIMIT; false = stop-loss (market)
  STOP_LOSS_LIMIT_OFFSET_BP: "10"    # limit is 10 bp (=0.10%) below the stop trigger

  # --- Exchange credentials (from repo Secrets) ---
  KRAKEN_API_KEY: ${{ secrets.KRAKEN_API_KEY }}
  KRAKEN_SECRET:  ${{ secrets.KRAKEN_API_SECRET }}   # <-- map to your existing secret
  # KRAKEN_PASSWORD: ${{ secrets.KRAKEN_PASSWORD }}  # not needed for Kraken spot; leave out

  # --- Cautious live knobs ---
  DRY_RUN: "false"        # set "true" for safe simulation
  TRADE_AMOUNT: "10"      # spend per buy in *quote* currency (USD/USDT)
  DAILY_CAP: "15"         # daily spend cap in quote currency

  # (Optional) selection defaults; ok to omit
  UNIVERSE_SIZE: "100"
  DROP_PCT: "2.0"
  PREFERRED_QUOTES: "USD,USDT"

jobs:
  trade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show runtime knobs
        run: |
          echo "DRY_RUN=${DRY_RUN}"
          echo "TRADE_AMOUNT=${TRADE_AMOUNT}"
          echo "DAILY_CAP=${DAILY_CAP}"
          echo "STOP_LOSS_PCT=${STOP_LOSS_PCT}"
          echo "STOP_LOSS_USE_LIMIT=${STOP_LOSS_USE_LIMIT}"
          echo "STOP_LOSS_LIMIT_OFFSET_BP=${STOP_LOSS_LIMIT_OFFSET_BP}"
          echo "DROP_PCT=${DROP_PCT}"
          echo "UNIVERSE_SIZE=${UNIVERSE_SIZE}"
          echo "PREFERRED_QUOTES=${PREFERRED_QUOTES}"

      - name: Run trader (Kraken)
        run: |
          python -V
          python main.py
