name: Crypto Live — Overnight (15m DRY-RUN by default)

on:
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: "ON for simulation, OFF for live trading"
        required: true
        default: "ON"
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: read

env:
  PYTHONUNBUFFERED: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

  # Bot knobs (from repo Variables, with sane defaults)
  MIN_BUY_USD:              ${{ vars.MIN_BUY_USD || '10' }}
  MAX_POSITIONS:            ${{ vars.MAX_POSITIONS || '3' }}
  MAX_BUYS_PER_RUN:         ${{ vars.MAX_BUYS_PER_RUN || '0' }}  # ← TEMP: halt new buys tonight
  UNIVERSE_TOP_K:           ${{ vars.UNIVERSE_TOP_K || '25' }}
  RESERVE_CASH_PCT:         ${{ vars.RESERVE_CASH_PCT || '5' }}
  DUST_MIN_USD:             ${{ vars.DUST_MIN_USD || '2' }}
  ROTATE_WHEN_FULL:         ${{ vars.ROTATE_WHEN_FULL || 'true' }}
  ROTATE_WHEN_CASH_SHORT:   ${{ vars.ROTATE_WHEN_CASH_SHORT || 'true' }}

  # Sell Guard (defaults; Variables can override)
  TAKE_PROFIT_PCT:          ${{ vars.TAKE_PROFIT_PCT || '12' }}
  TRAIL_PCT:                ${{ vars.TRAIL_PCT || '4' }}         # ← TEMP: a bit tighter so it actually trims
  STOP_LOSS_PCT:            ${{ vars.STOP_LOSS_PCT || '10' }}
  MIN_SELL_USD:             ${{ vars.MIN_SELL_USD || '10' }}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # Schedules are LIVE until you flip OFF/ON here.
      DRY_RUN: ${{ inputs.DRY_RUN || 'OFF' }}

      KRAKEN_API_KEY:    ${{ secrets.KRAKEN_API_KEY }}
      KRAKEN_API_SECRET: ${{ secrets.KRAKEN_API_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check for secrets
        run: |
          missing=0
          [ -z "${KRAKEN_API_KEY}" ]    && echo "❌ Missing secret: KRAKEN_API_KEY" && missing=1
          [ -z "${KRAKEN_API_SECRET}" ] && echo "❌ Missing secret: KRAKEN_API_SECRET" && missing=1
          if [ $missing -eq 1 ] && [ "${DRY_RUN}" = "OFF" ]; then
            echo "DRY_RUN=OFF but private API secrets are missing. Failing fast."
            exit 1
          fi
          echo "Secrets check complete."

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ccxt pandas pyyaml matplotlib

      - name: Create .state directory
        run: |
          mkdir -p .state
          echo "keep" > .state/.keep

      - name: Restore previous state (ok if first time)
        uses: actions/download-artifact@v4
        with:
          name: state_latest
          path: .state
        continue-on-error: true

      - name: Warm snapshots (balances/positions/buy_plan)
        run: python main.py --warm-only

      - name: Run trading loop
        run: |
          echo "=== START LOOP ==="
          python main.py --loop-once
          echo "=== END LOOP ==="

      - name: Upload state artifacts (rolling)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: state_latest
          path: .state
          if-no-files-found: warn
          retention-days: 7
