name: Crypto Live

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"

  STOP_LOSS_PCT: "2.0"              # % below filled buy price (e.g., 2.0 = 2%)
  STOP_LOSS_USE_LIMIT: "true"       # true = stop-loss-LIMIT; false = stop-loss (market)
  STOP_LOSS_LIMIT_OFFSET_BP: "10"   # limit is 10 bp (=0.10%) below the stop trigger

  # ---- Live knobs ----
  DRY_RUN: "false"              # set "true" for safe simulation
  TRADE_AMOUNT: "10"            # spend per buy in *quote* currency
  DAILY_CAP: "15"

  # ---- Signal / selection ----
  TIMEFRAME: "1m"               # fast candles so something triggers
  DROP_PCT: "0.0"               # accept any move (we’ll force-pick worst drop)
  FORCE_BUY: "true"             # if gate not met, buy top drop anyway

  # ---- Universe & liquidity ----
  UNIVERSE: "AUTO"              # <-- SCAN automatically (not a symbol)
  PREFERRED_QUOTES: "USD,USDT"  # prefer USD first (you have USD)
  MAX_SYMBOLS: "100"
  MIN_LAST_CANDLE_USD: "0"
  EXCLUDE: "USDT/USDT,USD/USDT"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ccxt

      - name: Show runtime knobs
        run: |
          echo "DRY_RUN=${DRY_RUN}"
          echo "TRADE_AMOUNT=${TRADE_AMOUNT}"
          echo "DROP_PCT=${DROP_PCT}"
          echo "TIMEFRAME=${TIMEFRAME}"
          echo "FORCE_BUY=${FORCE_BUY}"
          echo "UNIVERSE=${UNIVERSE}"
          echo "PREFERRED_QUOTES=${PREFERRED_QUOTES}"
          echo "MAX_SYMBOLS=${MAX_SYMBOLS}"
          echo "MIN_LAST_CANDLE_USD=${MIN_LAST_CANDLE_USD}"

      - name: Run trader (Kraken)
        env:
          DRY_RUN: ${{ env.DRY_RUN }}
          TRADE_AMOUNT: ${{ env.TRADE_AMOUNT }}
          DAILY_CAP: ${{ env.DAILY_CAP }}
          DROP_PCT: ${{ env.DROP_PCT }}
          SELL_DROP_PCT: "2.0"
          UNIVERSE: ${{ env.UNIVERSE }}
          PREFERRED_QUOTES: ${{ env.PREFERRED_QUOTES }}
          MAX_SYMBOLS: ${{ env.MAX_SYMBOLS }}
          MIN_LAST_CANDLE_USD: ${{ env.MIN_LAST_CANDLE_USD }}
          EXCLUDE: ${{ env.EXCLUDE }}
          TIMEFRAME: ${{ env.TIMEFRAME }}
          FORCE_BUY: ${{ env.FORCE_BUY }}
          KRAKEN_API_KEY: ${{ secrets.KRAKEN_API_KEY }}
          KRAKEN_API_SECRET: ${{ secrets.KRAKEN_API_SECRET }}
        run: |
          python -V
          python main.py
