name: Crypto Live (Every 15 min)

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

concurrency:
  group: crypto-live
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"

  # --- Stop-loss knobs ---
  STOP_LOSS_PCT: "2.0"
  STOP_LOSS_USE_LIMIT: "true"
  STOP_LOSS_LIMIT_OFFSET_BP: "10"

  # --- Live knobs ---
  DRY_RUN: "false"
  SKIP_BALANCE_PING: "true"          # NEW
  TRADE_AMOUNT: "15"
  DAILY_CAP: "50"
  DAILY_CAP_TZ: "America/Los_Angeles"

  # --- Selection / universe ---
  DROP_PCT: "2.0"
  UNIVERSE_SIZE: "100"
  PREFERRED_QUOTES: "USD,USDT"
  MIN_DOLLAR_VOL_24H: "500000"
  MIN_PRICE: "0.01"

  # --- Symbol controls ---
  EXCLUDE: "U/USD"
  # WHITELIST: "BTC/USD,ETH/USD,SOL/USD"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          (test -f requirements.txt && pip install -r requirements.txt) || true
          pip install ccxt

      - name: Show runtime knobs
        run: |
          echo "DRY_RUN=${DRY_RUN}"
          echo "SKIP_BALANCE_PING=${SKIP_BALANCE_PING}"
          echo "TRADE_AMOUNT=${TRADE_AMOUNT}"
          echo "DAILY_CAP=${DAILY_CAP}"
          echo "DAILY_CAP_TZ=${DAILY_CAP_TZ}"
          echo "STOP_LOSS_PCT=${STOP_LOSS_PCT}"
          echo "STOP_LOSS_USE_LIMIT=${STOP_LOSS_USE_LIMIT}"
          echo "STOP_LOSS_LIMIT_OFFSET_BP=${STOP_LOSS_LIMIT_OFFSET_BP}"
          echo "DROP_PCT=${DROP_PCT}"
          echo "UNIVERSE_SIZE=${UNIVERSE_SIZE}"
          echo "PREFERRED_QUOTES=${PREFERRED_QUOTES}"
          echo "MIN_DOLLAR_VOL_24H=${MIN_DOLLAR_VOL_24H}"
          echo "MIN_PRICE=${MIN_PRICE}"
          echo "EXCLUDE=${EXCLUDE}"
          echo "WHITELIST=${WHITELIST}"

      - name: Run trader (Kraken)
        env:
          DRY_RUN: ${{ env.DRY_RUN }}
          SKIP_BALANCE_PING: ${{ env.SKIP_BALANCE_PING }}
          TRADE_AMOUNT: ${{ env.TRADE_AMOUNT }}
          DAILY_CAP: ${{ env.DAILY_CAP }}
          DAILY_CAP_TZ: ${{ env.DAILY_CAP_TZ }}
          STOP_LOSS_PCT: ${{ env.STOP_LOSS_PCT }}
          STOP_LOSS_USE_LIMIT: ${{ env.STOP_LOSS_USE_LIMIT }}
          STOP_LOSS_LIMIT_OFFSET_BP: ${{ env.STOP_LOSS_LIMIT_OFFSET_BP }}
          DROP_PCT: ${{ env.DROP_PCT }}
          UNIVERSE_SIZE: ${{ env.UNIVERSE_SIZE }}
          PREFERRED_QUOTES: ${{ env.PREFERRED_QUOTES }}
          MIN_DOLLAR_VOL_24H: ${{ env.MIN_DOLLAR_VOL_24H }}
          MIN_PRICE: ${{ env.MIN_PRICE }}
          EXCLUDE: ${{ env.EXCLUDE }}
          WHITELIST: ${{ env.WHITELIST }}
          KRAKEN_API_KEY: ${{ secrets.KRAKEN_API_KEY }}
          KRAKEN_SECRET:  ${{ secrets.KRAKEN_API_SECRET }}
        run: |
          python -V
          python main.py
