name: Crypto Live - Overnight (15m DRY-RUN by default)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: "OFF to trade live; ON for dry run"
        type: choice
        required: true
        default: "ON"
        options: ["ON", "OFF"]
      RUN_SWITCH:
        description: "Global on/off (ON runs, OFF skips trading logic)"
        type: choice
        required: true
        default: "ON"
        options: ["ON", "OFF"]
      ADVANCED_JSON:
        description: "Optional advanced config JSON (sizing, caps, etc.)"
        required: false
        type: string
      PROTECT_JSON:
        description: "Optional guard/protect JSON (TP/SL/TSL, sell rules, etc.)"
        required: false
        type: string

concurrency:
  group: crypto-live-overnight
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  live:
    runs-on: ubuntu-latest

    env:
      DRY_RUN: ${{ inputs.DRY_RUN || 'ON' }}
      RUN_SWITCH: ${{ inputs.RUN_SWITCH || 'ON' }}

      MIN_BUY_USD:            ${{ vars.MIN_BUY_USD || '10' }}
      MAX_POSITIONS:          ${{ vars.MAX_POSITIONS || '3' }}
      MAX_BUYS_PER_RUN:       ${{ vars.MAX_BUYS_PER_RUN || '1' }}
      UNIVERSE_TOP_K:         ${{ vars.UNIVERSE_TOP_K || '25' }}
      RESERVE_CASH_PCT:       ${{ vars.RESERVE_CASH_PCT || '5' }}
      ROTATE_WHEN_FULL:       ${{ vars.ROTATE_WHEN_FULL || 'true' }}
      ROTATE_WHEN_CASH_SHORT: ${{ vars.ROTATE_WHEN_CASH_SHORT || 'true' }}
      MIN_SELL_USD:           ${{ vars.MIN_SELL_USD || '10' }}
      DUST_MIN_USD:           ${{ vars.DUST_MIN_USD || '2' }}
      DUST_SKIP_STABLES:      ${{ vars.DUST_SKIP_STABLES || 'true' }}

      ADVANCED_JSON: ${{ inputs.ADVANCED_JSON || '' }}
      PROTECT_JSON:  ${{ inputs.PROTECT_JSON  || '' }}

      STATE_DIR: ".state"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure .state exists (both levels)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ".state"
          mkdir -p "../.state"
          echo "sentinel: $(date -Iseconds)" > ".state/ARTIFACT_SENTINEL.txt"
          echo "sentinel: $(date -Iseconds)" > "../.state/ARTIFACT_SENTINEL.txt"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [[ -f requirements.txt ]]; then
            pip install -r requirements.txt
          else
            pip install pyyaml matplotlib pandas requests
          fi

      - name: Run trading bot
        id: run_bot
        shell: bash
        env:
          KRAKEN_API_KEY:    ${{ secrets.KRAKEN_API_KEY }}
          KRAKEN_API_SECRET: ${{ secrets.KRAKEN_API_SECRET }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          set -euo pipefail
          echo "DRY_RUN=${DRY_RUN}"
          echo "RUN_SWITCH=${RUN_SWITCH}"

          if [[ "${RUN_SWITCH}" != "ON" ]]; then
            echo "RUN_SWITCH is OFF -> skip trading logic."
            echo "skip" > "${STATE_DIR}/run_skipped.txt"
            exit 0
          fi

          {
            echo "=== Crypto Live Run ==="
            echo "started: $(date -Iseconds)"
            echo "DRY_RUN=${DRY_RUN}"
            echo "ADVANCED_JSON length: ${#ADVANCED_JSON}"
            echo "PROTECT_JSON length: ${#PROTECT_JSON}"
          } | tee "${STATE_DIR}/run_header.txt"

          python main.py
          echo "completed: $(date -Iseconds)" | tee -a "${STATE_DIR}/run_header.txt"

      - name: Generate KPI chart (optional)
        if: always() && hashFiles('tools/make_kpi_chart.py') != ''
        shell: bash
        run: |
          set -euo pipefail
          python tools/make_kpi_chart.py || echo "KPI chart generation skipped/failed."

      - name: Debug - locate .state folders
        if: always()
        shell: bash
        run: |
          set -euxo pipefail
          echo "WORKSPACE=${GITHUB_WORKSPACE}"
          find /home/runner/work -maxdepth 3 -type d -name ".state" -print || true
          echo "Repo .state files:"
          ( test -d ".state" && find .state -maxdepth 2 -type f ) || echo "none"
          echo "Parent .state files:"
          ( test -d "../.state" && find ../.state -maxdepth 2 -type f ) || echo "none"

      - name: Merge .state folders to one safe upload dir
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p safe_state
          if [[ -d ".state" ]]; then cp -r .state/* safe_state/ 2>/dev/null || true; fi
          if [[ -d "../.state" ]]; then cp -r ../.state/* safe_state/ 2>/dev/null || true; fi
          echo "safe_state contents:"
          find safe_state -type f -printf "%p (%s bytes)\n" || true

      - name: Upload merged .state artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: state-${{ github.run_id }}
          path: safe_state
          if-no-files-found: warn
          retention-days: 7
          compression-level: 6

      - name: Upload run report (optional)
        if: always() && hashFiles('safe_state/run_header.txt') != ''
        uses: actions/upload-artifact@v4
        with:
          name: run-report-${{ github.run_id }}
          path: safe_state/run_header.txt
          if-no-files-found: warn
          retention-days: 7

      - name: (Optional) Send Slack summary
        if: ${{ false }}
        shell: bash
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          set -euo pipefail
          if [[ -z "${SLACK_WEBHOOK_URL:-}" ]]; then
            echo "No webhook; skipping."
            exit 0
          fi
          msg="Crypto Live - Overnight finished run ${{ github.run_number }} (DRY_RUN=${DRY_RUN})"
          payload=$(printf '{"text":"%s"}' "$msg")
          curl -sS -X POST -H 'Content-type: application/json' --data "${payload}" "${SLACK_WEBHOOK_URL}" || true
