name: Crypto Live (Cautious - 15m)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes

jobs:
  cautious:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      DRY_RUN: "true"                # cautious default: dry-run until you flip this
      TRADE_AMOUNT: "10"
      MAX_TRADES_PER_RUN: "2"
      TP: "0.015"
      SL: "0.03"
      TRAIL: "0.02"
      DROP_PCT: "0.01"
      MIN_NOTIONAL_BUFFER: "1.0"
      TIMEFRAME: "5m"
      SMA_LEN: "10"
      SYMBOLS: "DOGE/USD,XRP/USD,ADA/USD,ETH/USD,BTC/USD"

      KRAKEN_API_KEY: ${{ secrets.KRAKEN_API_KEY }}
      KRAKEN_SECRET:  ${{ secrets.KRAKEN_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ccxt

      - name: Run trader
        run: |
          set -e
          python --version
          python main.py
