name: Crypto Live (15m)

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  poke:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: |
          echo "Hello from cron"
          date -u
