name: Equities Live (9:35 & 3:50 ET — SAFE)

on:
  workflow_dispatch:
  schedule:
    # 9:35 AM ET (13:35 UTC)
    - cron: '35 13 * * 1-5'
    # 3:50 PM ET (19:50 UTC)
    - cron: '50 19 * * 1-5'

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run equities trader
        env:
          ROBINHOOD_USERNAME: ${{ secrets.ROBINHOOD_USERNAME }}
          ROBINHOOD_PASSWORD: ${{ secrets.ROBINHOOD_PASSWORD }}
          ROBINHOOD_MFA: ${{ secrets.ROBINHOOD_MFA }}
          STATE_DIR: .state
          MARKET: equities
          DRY_RUN: "true"   # flip to "false" when ready
          PER_TRADE_USD: "10"
          DAILY_CAP_USD: "20"
        run: |
          python main.py
