name: Equities Live — Alpaca 1D Bars (Auto-Pick)

on:
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: "true or false"
        required: true
        default: "false"
      PER_TRADE_USD:
        description: "USD notional per buy"
        required: true
        default: "3"
      DAILY_CAP_USD:
        description: "USD daily spend cap"
        required: true
        default: "12"
      UNIVERSE:
        description: "Used only if AUTO_PICK=false (comma list)"
        required: true
        default: "AAPL,MSFT"
      MARKET_ONLY:
        description: "true to use market orders"
        required: true
        default: "true"
      AUTO_PICK:
        description: "true = scan & auto-pick top names"
        required: true
        default: "true"
      PICKS_PER_RUN:
        description: "how many symbols to buy max"
        required: true
        default: "6"
      MIN_ADV_USD:
        description: "Min avg $ volume (20d) for eligibility (IEX feed)"
        required: true
        default: "2000000"
      AVOID_REBUY:
        description: "true = don't buy if already holding"
        required: true
        default: "false"
      MIN_BUYS:
        description: "Minimum buys per run (0 disables fallback)"
        required: true
        default: "1"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy alpaca-py yfinance
          fi

      - name: Run Equities Engine
        env:
          DRY_RUN:        ${{ github.event.inputs.DRY_RUN }}
          PER_TRADE_USD:  ${{ github.event.inputs.PER_TRADE_USD }}
          DAILY_CAP_USD:  ${{ github.event.inputs.DAILY_CAP_USD }}
          UNIVERSE:       ${{ github.event.inputs.UNIVERSE }}
          MARKET_ONLY:    ${{ github.event.inputs.MARKET_ONLY }}
          AUTO_PICK:      ${{ github.event.inputs.AUTO_PICK }}
          PICKS_PER_RUN:  ${{ github.event.inputs.PICKS_PER_RUN }}
          MIN_ADV_USD:    ${{ github.event.inputs.MIN_ADV_USD }}
          AVOID_REBUY:    ${{ github.event.inputs.AVOID_REBUY }}
          MIN_BUYS:       ${{ github.event.inputs.MIN_BUYS }}

          # Alpaca (Paper)
          ALPACA_API_KEY:     ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY:  ${{ secrets.ALPACA_SECRET_KEY }}
          ALPACA_PAPER:       "true"

          LOG_LEVEL: "INFO"
        run: |
          python trader/equities_engine.py
