name: equities-daily

on:
  # Weekdays ~09:35 ET (13:35 UTC) – adjust if you like
  schedule:
    - cron: "35 13 * * 1-5"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry-run mode? (true/false)"
        required: true
        default: "true"
      symbols:
        description: "Comma-separated equity symbols (e.g., AAPL,MSFT) — leave a single space to reuse last or defaults"
        required: true
        default: "AAPL,MSFT"
      start:
        description: "Start date (YYYY-MM-DD)"
        required: true
        default: "2023-01-01"
      end:
        description: "End date (YYYY-MM-DD, empty=today)"
        required: false
        default: ""
      equity_dollars:
        description: "EQUITY dollars per trade"
        required: false
        default: "200"
      force_side:
        description: "Force side for equities (buy/sell or empty)"
        required: false
        default: ""
      equity_autopick:
        description: "Autopick equities top movers? (true/false)"
        required: false
        default: "false"
      advanced_json:
        description: "Optional JSON for advanced settings (size rules, max positions, etc.)"
        required: false
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest

    # Defaults for scheduled runs; workflow_dispatch inputs override via ternaries below
    env:
      OUT_DIR: out
      # brokers/exchange
      EQUITY_BROKER: robinhood
      CRYPTO_EXCHANGE: kraken
      RH_USERNAME: ${{ secrets.RH_USERNAME }}
      RH_PASSWORD: ${{ secrets.RH_PASSWORD }}
      RH_TOTP_SECRET: ${{ secrets.RH_TOTP_SECRET }}
      CRYPTO_API_KEY: ${{ secrets.CRYPTO_API_KEY }}
      CRYPTO_API_SECRET: ${{ secrets.CRYPTO_API_SECRET }}
      CRYPTO_API_PASSPHRASE: ${{ secrets.CRYPTO_API_PASSPHRASE }}

      # ---- runtime config (equities only) ----
      DRY_RUN: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || 'true' }}
      SYMBOLS: ${{ github.event_name == 'workflow_dispatch' && inputs.symbols || 'AAPL,MSFT' }}
      START: ${{ github.event_name == 'workflow_dispatch' && inputs.start || '2023-01-01' }}
      END:   ${{ github.event_name == 'workflow_dispatch' && inputs.end   || '' }}
      EQUITY_DOLLARS_PER_TRADE: ${{ github.event_name == 'workflow_dispatch' && inputs.equity_dollars || '200' }}
      CRYPTO_DOLLARS_PER_TRADE: "0"                           # off for this workflow
      FORCE_SIDE: ${{ github.event_name == 'workflow_dispatch' && inputs.force_side || '' }}

      # autopick flags – equities optional, crypto off
      CRYPTO_AUTOPICK: "false"
      EQUITY_AUTOPICK: ${{ github.event_name == 'workflow_dispatch' && inputs.equity_autopick || 'false' }}
      AUTOPICK_OVERRIDES: ${{ github.event_name == 'workflow_dispatch' && inputs.advanced_json || '' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        run: |
          echo "CONFIG:"
          echo "  dry_run=$DRY_RUN"
          echo "  symbols=$SYMBOLS"
          echo "  start=$START end=$END"
          echo "  crypto_autopick=$CRYPTO_AUTOPICK equity_autopick=$EQUITY_AUTOPICK"
          echo "  force_side=$FORCE_SIDE"
          python main.py

      - name: List out/
        run: |
          echo "Listing out/:"
          ls -la out || true

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: trade-outputs.zip
          path: out/
          if-no-files-found: warn
