name: Equities Live (Paper, every 15m)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * 1-5"

permissions:
  contents: read

concurrency:
  group: equities-live
  cancel-in-progress: true

jobs:
  trade:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      # --- Trading config (PAPER “blast it”) ---
      DRY_RUN: "false"                 # live Paper trades
      PER_TRADE_USD: "2000"            # dollars per new position
      MAX_POSITIONS: "20"              # allow up to 20 open paper positions
      BUY_PER_RUN: "5"                 # buy up to 5 new names per run (subject to slots/cash)
      TP_PCT: "0.035"                  # 3.5% take-profit (bracket)
      SL_PCT: "0.020"                  # 2.0% stop-loss (bracket)
      UNIVERSE: "SPY,QQQ,VOO,AAPL,MSFT,NVDA,AMD,AVGO,META,GOOGL,AMZN,TSLA,SMCI,ORCL,INTC,CRM,COST,UNH,LIN,PEP,ADBE,TMUS,ASML,NFLX,TXN,AMAT,PLTR,MA,V,IBM,DE,BA,GE,ABBV,MRK,PFE,JNJ,WMT,MCD,NKE,XOM,CVX"
      LOG_LEVEL: "INFO"

      # --- Alpaca credentials ---
      ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
      ALPACA_API_SECRET: ${{ secrets.ALPACA_API_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "alpaca-py>=0.42.1" pandas yfinance pytz tenacity

      - name: Run Equities Engine
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python -u trader/equities_engine.py
