# FILE: trader/broker_alpaca.py
# Alpaca Equities broker wrapper — PAPER by default
# - Minimal deps (uses built-in json, time, math, and requests)
# - Position-aware sells
# - Market buys sized by USD notional (Alpaca submits qty; we derive qty from latest price)
# - Min order guard
# - DRY_RUN toggle (simulates without hitting the API)
#
# ENV VARS (expected)
#   ALPACA_API_KEY
#   ALPACA_API_SECRET
#   ALPACA_BASE_URL   (default: https://paper-api.alpaca.markets)
#   ALPACA_DATA_URL   (default: https://data.alpaca.markets)
#   DRY_RUN           ("true"/"false")
#
# Typical usage (inside your main.py):
#   from trader.broker_alpaca import AlpacaEquitiesBroker
#   broker = AlpacaEquitiesBroker(dry_run=os.getenv("DRY_RUN","true").lower()=="true")
#   cash = broker.get_cash()
#   px = broker.get_latest_price("AAPL")
#   broker.market_buy_usd("AAPL", 25)
#   broker.market_sell_all("AAPL")

from __future__ import annotations
from typing import Optional, Dict, Any
import os, time, math, json
import requests


class AlpacaHTTPError(Exception):
    pass


class AlpacaEquitiesBroker:
    """
    Thin wrapper around Alpaca REST for equities.
    - PAPER by default (base_url defaults to paper)
    - Market buys in USD notional (compute qty from latest price)
    - Position-aware sells
    - Min notional guard
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        api_secret: Optional[str] = None,
        base_url: Optional[str] = None,
        data_url: Optional[str] = None,
        dry_run: bool = True,
        min_notional_usd: float = 1.00,
        price_slippage_pad: float = 0.003,  # +0.3% pad when estimating qty
        session: Optional[requests.Session] = None,
    ) -> None:
        self.api_key = api_key or os.getenv("ALPACA_API_KEY", "")
        self.api_secret = api_secret or os.getenv("ALPACA_API_SECRET", "")
        self.base_url = base_url or os.getenv("ALPACA_BASE_URL", "https://paper-api.alpaca.markets")
        self.data_url = data_url or os.getenv("ALPACA_DATA_URL", "https://data.alpaca.markets")
        self.dry_run = dry_run
        self.min_notional_usd = float(os.getenv("MIN_NOTIONAL_USD", min_notional_usd))
        self.price_slippage_pad = price_slippage_pad
        self._s = session or requests.Session()

        if not self.dry_run and (not self.api_key or not self.api_secret):
            raise ValueError("ALPACA_API_KEY/SECRET are required for live API calls")

    # ------------------------
    # Internal helpers
    # ------------------------
    def _headers(self) -> Dict[str, str]:
        return {
            "APCA-API-KEY-ID": self.api_key,
            "APCA-API-SECRET-KEY": self.api_secret,
            "Content-Type": "application/json",
        }

    def _get(self, path: str, params: Optional[Dict[str, Any]] = None, data_api: bool = False) -> Any:
        url = (self.data_url if data_api else self.base_url).rstrip("/") + path
        r = self._s.get(url, headers=self._headers(), params=params, timeout=20)
        if r.status_code >= 300:
            raise AlpacaHTTPError(f"GET {path} -> {r.status_code}: {r.text[:300]}")
        return r.json()

    def _post(self, path: str, payload: Dict[str, Any]) -> Any:
        url = self.base_url.rstrip("/") + path
        r = self._s.post(url, headers=self._headers(), data=json.dumps(payload), timeout=20)
        if r.status_code >= 300:
            raise AlpacaHTTPError(f"POST {path} -> {r.status_code}: {r.text[:300]}")
        return r.json()

    # ------------------------
    # Public API
    # ------------------------
    def get_account(self) -> Dict[str, Any]:
        if self.dry_run:
            # Simulated structure
            return {
                "currency": "USD",
                "cash": os.getenv("SIM_CASH", "10000.00"),
                "portfolio_value": os.getenv("SIM_PV", "10000.00"),
                "status": "DRY_RUN",
            }
        return self._get("/v2/account")

    def get_cash(self) -> float:
        acct = self.get_account()
        cash_str = acct.get("cash") or acct.get("buying_power") or "0"
        try:
            return float(cash_str)
        except Exception:
            return 0.0

    def get_positions(self) -> Dict[str, Dict[str, Any]]:
        if self.dry_run:
            # No persisted sim positions here; your main.py should persist .state/positions.json
            return {}
        rows = self._get("/v2/positions")
        out: Dict[str, Dict[str, Any]] = {}
        for p in rows:
            out[p["symbol"].upper()] = p
        return out

    def get_position(self, symbol: str) -> Optional[Dict[str, Any]]:
        symbol = symbol.upper()
        positions = self.get_positions()
        return positions.get(symbol)

    def get_latest_price(self, symbol: str) -> Optional[float]:
        symbol = symbol.upper()
        try:
            q = self._get(f"/v2/stocks/{symbol}/trades/latest", data_api=True)
            px = q.get("trade", {}).get("p")
            return float(px) if px is not None else None
        except Exception:
            # fallback try quote endpoint
            try:
                q = self._get(f"/v2/stocks/{symbol}/quotes/latest", data_api=True)
                px = q.get("quote", {}).get("ap") or q.get("quote", {}).get("bp")
                return float(px) if px is not None else None
            except Exception:
                return None

    def market_buy_usd(self, symbol: str, usd: float) -> Dict[str, Any]:
        symbol = symbol.upper()
        usd = float(usd)
        if usd < self.min_notional_usd:
            return {"status": "blocked", "reason": f"below_min_notional {usd} < {self.min_notional_usd}"}

        px = self.get_latest_price(symbol)
        if not px or px <= 0:
            return {"status": "blocked", "reason": f"no_price {symbol}"}

        qty = usd / (px * (1 + self.price_slippage_pad))
        # Alpaca requires qty > 0 and shares in decimals are allowed for some symbols via fractional trading
        qty = max(0.0001, round(qty, 4))

        if self.dry_run:
            return {
                "status": "simulated",
                "side": "buy",
                "symbol": symbol,
                "notional_usd": round(usd, 2),
                "est_price": round(px, 4),
                "est_qty": qty,
            }

        payload = {
            "symbol": symbol,
            "qty": str(qty),
            "side": "buy",
            "type": "market",
            "time_in_force": "day",
        }
        o = self._post("/v2/orders", payload)
        return {"status": "submitted", "order": o}

    def market_sell_qty(self, symbol: str, qty: float) -> Dict[str, Any]:
        symbol = symbol.upper()
        qty = float(qty)
        if qty <= 0:
            return {"status": "blocked", "reason": "qty<=0"}

        if self.dry_run:
            return {
                "status": "simulated",
                "side": "sell",
                "symbol": symbol,
                "qty": round(qty, 4),
            }

        payload = {
            "symbol": symbol,
            "qty": str(round(qty, 4)),
            "side": "sell",
            "type": "market",
            "time_in_force": "day",
        }
        o = self._post("/v2/orders", payload)
        return {"status": "submitted", "order": o}

    def market_sell_all(self, symbol: str) -> Dict[str, Any]:
        symbol = symbol.upper()
        pos = self.get_position(symbol)
        if not pos:
            return {"status": "blocked", "reason": f"no_position {symbol}"}
        try:
            qty = float(pos.get("qty"))
        except Exception:
            qty = 0.0
        if qty <= 0:
            return {"status": "blocked", "reason": f"zero_qty {symbol}"}
        return self.market_sell_qty(symbol, qty)

    # convenience
    def ping(self) -> bool:
        try:
            _ = self.get_account()
            return True
        except Exception:
            return False


# Optional quick self-test
if __name__ == "__main__":
    b = AlpacaEquitiesBroker(dry_run=True)
    print("Account:", b.get_account())
    print("Cash:", b.get_cash())
    print("AAPL px:", b.get_latest_price("AAPL"))
    print("Buy sim:", b.market_buy_usd("AAPL", 25))


# -------------------------------------------------------------
# FILE: .github/workflows/equities-live.yml
# Equities Live (Alpaca) — PAPER first (YAML fix)
# - Schedules: 9:35am ET and 3:50pm ET on weekdays (cron in UTC)
# - DRY_RUN defaults to true; safe paper test
# -------------------------------------------------------------

name: Equities Live (Alpaca — PAPER)

on:
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: "Dry run (paper)? true/false"
        required: false
        default: "true"
      PER_TRADE_USD:
        description: "USD per trade"
        required: false
        default: "25"
      DAILY_CAP_USD:
        description: "Max USD spent per day"
        required: false
        default: "50"
      UNIVERSE:
        description: "Comma-separated tickers"
        required: false
        default: "SPY,AAPL,MSFT,TSLA,NVDA,AMD"
  schedule:
    - cron: "35 13 * * 1-5"   # 09:35 ET during EDT
    - cron: "50 19 * * 1-5"   # 15:50 ET during EDT

jobs:
  trade:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Export env (safe defaults)
        env:
          IN_DRY: ${{ github.event.inputs.DRY_RUN }}
          IN_PT: ${{ github.event.inputs.PER_TRADE_USD }}
          IN_DC: ${{ github.event.inputs.DAILY_CAP_USD }}
          IN_UNI: ${{ github.event.inputs.UNIVERSE }}
        run: |
          # DRY_RUN default to true when not provided (scheduled runs)
          if [ -z "$IN_DRY" ]; then echo "DRY_RUN=true" >> $GITHUB_ENV; else echo "DRY_RUN=$IN_DRY" >> $GITHUB_ENV; fi
          # Other inputs with fallbacks
          if [ -z "$IN_PT" ]; then echo "PER_TRADE_USD=25" >> $GITHUB_ENV; else echo "PER_TRADE_USD=$IN_PT" >> $GITHUB_ENV; fi
          if [ -z "$IN_DC" ]; then echo "DAILY_CAP_USD=50" >> $GITHUB_ENV; else echo "DAILY_CAP_USD=$IN_DC" >> $GITHUB_ENV; fi
          if [ -z "$IN_UNI" ]; then echo "UNIVERSE=SPY,AAPL,MSFT,TSLA,NVDA,AMD" >> $GITHUB_ENV; else echo "UNIVERSE=$IN_UNI" >> $GITHUB_ENV; fi
          echo "BROKER=alpaca" >> $GITHUB_ENV
          echo "ASSET_CLASS=equities" >> $GITHUB_ENV
          echo "AUTO_UNIVERSE=1" >> $GITHUB_ENV
          echo "MIN_NOTIONAL_USD=1.00" >> $GITHUB_ENV
          # PAPER endpoints by default
          echo "ALPACA_BASE_URL=https://paper-api.alpaca.markets" >> $GITHUB_ENV
          echo "ALPACA_DATA_URL=https://data.alpaca.markets" >> $GITHUB_ENV

      - name: Inject secrets (Alpaca)
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_API_SECRET: ${{ secrets.ALPACA_API_SECRET }}
        run: |
          if [ -z "$ALPACA_API_KEY" ] || [ -z "$ALPACA_API_SECRET" ]; then
            echo "Missing ALPACA secrets; ensure repo secrets are set. For paper runs DRY_RUN must be true." && exit 1
          fi
          echo "ALPACA_API_KEY=$ALPACA_API_KEY" >> $GITHUB_ENV
          echo "ALPACA_API_SECRET=$ALPACA_API_SECRET" >> $GITHUB_ENV

      - name: Sanity check broker ping (paper)
        run: |
          python - << 'PY'
          import os
          from trader.broker_alpaca import AlpacaEquitiesBroker
          dry = os.getenv('DRY_RUN','true').lower()=='true'
          b = AlpacaEquitiesBroker(dry_run=dry)
          print('DRY_RUN =', dry)
          print('Ping =', b.ping())
          print('Cash =', b.get_cash())
          print('AAPL px =', b.get_latest_price('AAPL'))
          PY

      - name: Run trader
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          set -e
          echo "=== ENV ==="; env | sort
          echo "=== START MAIN ==="
          if [ -f "main.py" ]; then
            python main.py --asset equities --broker alpaca || python main.py
          elif [ -f "trader/main.py" ]; then
            python trader/main.py --asset equities --broker alpaca || python trader/main.py
          else
            echo "No main.py found. Please update the run step to your entry point."; exit 2
          fi

      - name: Mark success
        if: ${{ success() }}
        run: echo "Equities (Alpaca — PAPER) run completed."
