name: Equities Live (Paper, every 15m)

on:
  workflow_dispatch:
  schedule:
    # Run every 15 minutes on weekdays. The script itself checks the Alpaca clock
    # and exits instantly if the market is closed or outside regular hours.
    - cron: "*/15 * * * 1-5"

permissions:
  contents: read

concurrency:
  group: equities-live
  cancel-in-progress: true

jobs:
  trade:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      # --- Trading config ---
      DRY_RUN: "false"                 # keep false for live Paper trades
      EXCHANGE: "alpaca"
      PER_TRADE_USD: "25"             # dollars per new position
      MAX_POSITIONS: "3"              # cap how many open positions we allow
      TP_PCT: "0.035"                 # 3.5% take-profit (bracket order)
      SL_PCT: "0.020"                 # 2.0% stop-loss (bracket order)
      UNIVERSE: "SPY,AAPL,MSFT,AMD,NVDA,QQQ,TSLA,SMCI,META,GOOGL"
      LOG_LEVEL: "INFO"

      # --- Alpaca credentials ---
      ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
      ALPACA_API_SECRET: ${{ secrets.ALPACA_API_SECRET }}
      ALPACA_BASE_URL: ${{ secrets.ALPACA_BASE_URL }} # e.g. https://paper-api.alpaca.markets

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install alpaca-py pandas yfinance pytz tenacity

      - name: Run Equities Engine
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python -u trader/equities_engine.py
