name: Equities Daily — Auto-Pick (Open + Close)

on:
  # GitHub Actions cron runs in UTC.
  # Sep–Nov 2025 is EDT (UTC−4), so:
  #   09:40 ET  => 13:40 UTC
  #   15:50 ET  => 19:50 UTC
  schedule:
    - cron: "40 13 * * 1-5"  # ~9:40 AM ET (post-open scan)
    - cron: "50 19 * * 1-5"  # ~3:50 PM ET (pre-close pass)
  # Keep a manual button too (no inputs to avoid the 10-input cap)
  workflow_dispatch:

permissions:
  contents: read

# Prevent overlapping daily runs and avoid colliding with manual runs
concurrency:
  group: equities-daily
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy alpaca-py yfinance
          fi

      - name: Run Equities Engine (Scheduled)
        env:
          # Defaults for scheduled runs; override inside code if desired.
          DRY_RUN:             "false"
          PER_TRADE_USD:       "3"
          DAILY_CAP_USD:       "12"
          UNIVERSE:            "AAPL,MSFT"
          AUTO_PICK:           "true"
          PICKS_PER_RUN:       "6"
          MIN_ADV_USD:         "2000000"
          AVOID_REBUY:         "true"
          STOP_LOSS_PCT:       "0.04"
          TAKE_PROFIT_PCT:     "0.08"
          MARKET_ONLY:         "true"
          SELL_ON_TREND_BREAK: "true"

          # Alpaca (Paper)
          ALPACA_API_KEY:     ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY:  ${{ secrets.ALPACA_SECRET_KEY }}
          ALPACA_PAPER:       "true"

          LOG_LEVEL: "INFO"
        run: |
          python trader/equities_engine.py
