name: Force Sell (one-time)

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (no real orders)?"
        required: true
        default: "true"
        type: choice
        options: ["true","false"]
      sell_debug:
        description: "Verbose sell checks? 1=yes, 0=no"
        required: true
        default: "1"
        type: choice
        options: ["1","0"]

jobs:
  force_sell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install ccxt; fi

      - name: Apply env (force sell)
        run: |
          echo "MODE=live" >> $GITHUB_ENV
          echo "DRY_RUN=${{ inputs.dry_run }}" >> $GITHUB_ENV
          echo "SELL_DEBUG=${{ inputs.sell_debug }}" >> $GITHUB_ENV
          echo "FORCE_SELL=1" >> $GITHUB_ENV

      - name: Run trader (force sells only)
        run: |
          mkdir -p .state data
          python -u main.py
