name: Momentum Spike — Collector (DRY)

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes UTC
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # CLEAN defaults (numbers only). Repo Variables override these when present.
    env:
      MIN_BASE_VOL_USD: ${{ vars.MIN_BASE_VOL_USD || '25000' }}
      MIN_24H_PCT:      ${{ vars.MIN_24H_PCT      || '25' }}
      MOMENTUM_EMA_WINDOW: ${{ vars.MOMENTUM_EMA_WINDOW || '10' }}
      MAX_CANDIDATES:      ${{ vars.MAX_CANDIDATES      || '10' }}
      QUOTE_WHITELIST:     ${{ vars.QUOTE_WHITELIST     || 'USD,USDT' }}
      OHLCV_TIMEFRAME:     ${{ vars.OHLCV_TIMEFRAME     || '15m' }}
      MAX_MARKETS:         ${{ vars.MAX_MARKETS         || '500' }}
      OUTPUT_DIR: .state
      LOG_LEVEL: INFO

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          # ensure ccxt present even if not pinned
          python - << 'PY'
          import importlib, sys, subprocess
          try:
              importlib.import_module("ccxt")
          except Exception:
              subprocess.check_call([sys.executable, "-m", "pip", "install", "ccxt"])
          PY

      - name: Run Momentum Spike Collector (DRY)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$OUTPUT_DIR"
          echo "ENV DUMP >>>"
          echo "MIN_BASE_VOL_USD=$MIN_BASE_VOL_USD"
          echo "MIN_24H_PCT=$MIN_24H_PCT"
          echo "MOMENTUM_EMA_WINDOW=$MOMENTUM_EMA_WINDOW"
          echo "MAX_CANDIDATES=$MAX_CANDIDATES"
          echo "QUOTE_WHITELIST=$QUOTE_WHITELIST"
          echo "OHLCV_TIMEFRAME=$OHLCV_TIMEFRAME"
          echo "MAX_MARKETS=$MAX_MARKETS"
          echo "OUTPUT_DIR=$OUTPUT_DIR"
          echo "<<< ENV DUMP"
          python spike_scan.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: momentum-spike-output
          path: |
            .state/spike_candidates.csv
