name: Risk Signal Notifier

on:
  schedule:
    - cron: "0 14 * * *"   # 14:00 UTC daily (adjust anytime)
  workflow_dispatch: {}

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Read current signal
        id: now
        run: |
          CURR="OFF"
          if [ -f ".state/risk_signal.txt" ]; then
            RAW=$(cat .state/risk_signal.txt | tr -d '\r' | tr '[:lower:]' '[:upper:]')
            if [ "$RAW" = "ON" ] || [ "$RAW" = "OFF" ]; then
              CURR="$RAW"
            fi
          fi
          echo "curr=$CURR" >> "$GITHUB_OUTPUT"

      - name: Compare to last value
        id: cmp
        run: |
          LAST="UNKNOWN"
          if [ -f ".state/last_risk_signal.txt" ]; then
            LAST=$(cat .state/last_risk_signal.txt | tr -d '\r')
          fi
          echo "last=$LAST" >> "$GITHUB_OUTPUT"
          echo "${{ steps.now.outputs.curr }}" > .state/last_risk_signal.txt

      - name: Slack alert on flip (color card)
        if: ${{ env.SLACK_WEBHOOK_URL != '' && steps.cmp.outputs.last != 'UNKNOWN' && steps.cmp.outputs.last != steps.now.outputs.curr }}
        run: |
          COLOR="#2eb886"
          ICON="🟢"
          if [ "${{ steps.now.outputs.curr }}" = "OFF" ]; then
            COLOR="#e01e5a"
            ICON="🔴"
          fi
          read -r -d '' PAYLOAD <<'JSON'
          {
            "attachments": [
              {
                "color": "COLOR_HERE",
                "title": "ICON_HERE Risk flip",
                "fields": [
                  {"title":"From","value":"LAST_HERE","short":true},
                  {"title":"To","value":"CURR_HERE","short":true}
                ],
                "ts": TIMESTAMP_HERE
              }
            ]
          }
JSON
          TS=$(date +%s)
          PAYLOAD=${PAYLOAD//COLOR_HERE/$COLOR}
          PAYLOAD=${PAYLOAD//ICON_HERE/$ICON}
          PAYLOAD=${PAYLOAD//LAST_HERE/${{ steps.cmp.outputs.last }}}
          PAYLOAD=${PAYLOAD//CURR_HERE/${{ steps.now.outputs.curr }}}
          PAYLOAD=${PAYLOAD//TIMESTAMP_HERE/$TS}
          curl -X POST -H 'Content-type: application/json' \
            --data "$PAYLOAD" \
            "${SLACK_WEBHOOK_URL}"

      - name: Save last value
        uses: actions/upload-artifact@v4
        with:
          name: risk-state
          path: .state/last_risk_signal.txt
