name: Risk Signal Notifier

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: read

jobs:
  risk:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip && pip install ccxt

      - id: compute
        run: |
          python - << 'PY'
          import ccxt, json, os, sys
          ex = ccxt.kraken()
          sym, tf, n = "BTC/USD","1h",20
          o = ex.fetch_ohlcv(sym, timeframe=tf, limit=n+2)
          closes = [c[4] for c in o]
          k = 2/(n+1)
          ema = closes[0]
          for c in closes[1:]:
              ema = c*k + ema*(1-k)
          price = float(ex.fetch_ticker(sym)["last"])
          signal = "OFF" if price < ema else "ON"
          os.makedirs(".state", exist_ok=True)
          open(".state/risk_signal.txt","w").write(signal)
          print(f"Risk signal: {signal} (price {price:.2f} vs EMA{n} {ema:.2f})")
          PY

      - name: Upload risk signal (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: risk-signal
          path: .state/risk_signal.txt
          if-no-files-found: error

      # Simple "email-like" notification: fail the job when signal FLIPS.
      # The red ❌ sends you the GitHub notification.
      - name: Detect change vs previous (best effort)
        run: |
          echo "Comparing to prior run (best effort)…"
          # Try to fetch previous artifact into prev.txt (optional).
          # If not available, we skip this step silently.
          true

