name: headless-trader

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry-run mode? (true/false)"
        required: true
        default: "true"
      symbols:
        description: "Comma-separated symbols"
        required: true
        default: "AAPL,MSFT,BTC-USD"
      start:
        description: "Start date (YYYY-MM-DD)"
        required: true
        default: "2023-01-01"
      end:
        description: "End date (YYYY-MM-DD, empty=today)"
        required: false
        default: ""
  schedule:
    # --- Market OPEN ~ 9:35 AM US/Eastern ---
    - cron: "35 13 * 3-10 1-5"  # Mar–Oct (DST): 13:35 UTC
    - cron: "35 14 * 11-2 1-5"  # Nov–Feb (Standard): 14:35 UTC

    # --- Market CLOSE ~ 4:05 PM US/Eastern ---
    - cron: "05 20 * 3-10 1-5"  # Mar–Oct (DST): 20:05 UTC
    - cron: "05 21 * 11-2 1-5"  # Nov–Feb (Standard): 21:05 UTC

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run trader (main.py)
        env:
          SYMBOLS: ${{ github.event.inputs.symbols || 'AAPL,MSFT,BTC-USD' }}
          START:   ${{ github.event.inputs.start   || '2023-01-01' }}
          END:     ${{ github.event.inputs.end     || '' }}
          DRY_RUN: ${{ github.event.inputs.dry_run || 'true' }}
          OUT_DIR: out

          # Optional brokers (safe if unset)
          EQUITY_BROKER: robinhood
          RH_USERNAME:      ${{ secrets.RH_USERNAME }}
          RH_PASSWORD:      ${{ secrets.RH_PASSWORD }}
          RH_TOTP_SECRET:   ${{ secrets.RH_TOTP_SECRET }}
          RH_DEVICE_TOKEN:  ${{ secrets.RH_DEVICE_TOKEN }}

          CRYPTO_EXCHANGE:        ${{ vars.CRYPTO_EXCHANGE }}
          CRYPTO_API_KEY:         ${{ secrets.CRYPTO_API_KEY }}
          CRYPTO_API_SECRET:      ${{ secrets.CRYPTO_API_SECRET }}
          CRYPTO_API_PASSPHRASE:  ${{ secrets.CRYPTO_API_PASSPHRASE }}
        run: |
          python main.py

      - name: List outputs (for diagnostics)
        run: |
          echo "Listing out/ (if it exists):"
          ls -lah out || true

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: trade-outputs
          path: out/**
          if-no-files-found: warn
