name: headless-trader-live

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry-run mode? (true/false)"
        required: true
        default: "false"            # LIVE by default
      symbols:
        description: "Comma-separated symbols (equities &/or crypto). Put a single space to let autopick handle crypto."
        required: true
        default: "BTC-USD"
      start:
        description: "Start date (YYYY-MM-DD)"
        required: true
        default: "2023-01-01"
      end:
        description: "End date (YYYY-MM-DD, empty=today)"
        required: false
        default: ""
      equity_dollars:
        description: "EQUITY dollars per trade"
        required: false
        default: "200"
      crypto_dollars:
        description: "CRYPTO dollars per trade"
        required: false
        default: "5"
      force_side:
        description: "Force side for crypto (buy/sell or empty)"
        required: false
        default: ""
      crypto_autopick:
        description: "Autopick crypto top movers? (true/false)"
        required: false
        default: "true"
      equity_autopick:
        description: "Autopick equities top movers? (true/false)"
        required: false
        default: "false"
      advanced_json:
        description: "Optional JSON for advanced settings (size rules, max positions, etc.)"
        required: false
        default: ""

concurrency:
  group: trader-live
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OUT_DIR: out
      EQUITY_BROKER: robinhood
      CRYPTO_EXCHANGE: kraken

      # secrets
      RH_USERNAME: ${{ secrets.RH_USERNAME }}
      RH_PASSWORD: ${{ secrets.RH_PASSWORD }}
      RH_TOTP_SECRET: ${{ secrets.RH_TOTP_SECRET }}
      CRYPTO_API_KEY: ${{ secrets.CRYPTO_API_KEY }}
      CRYPTO_API_SECRET: ${{ secrets.CRYPTO_API_SECRET }}
      CRYPTO_API_PASSPHRASE: ${{ secrets.CRYPTO_API_PASSPHRASE }}

      # inputs -> env
      DRY_RUN: ${{ inputs.dry_run }}
      SYMBOLS: ${{ inputs.symbols }}
      START: ${{ inputs.start }}
      END: ${{ inputs.end }}
      EQUITY_DOLLARS_PER_TRADE: ${{ inputs.equity_dollars }}
      CRYPTO_DOLLARS_PER_TRADE: ${{ inputs.crypto_dollars }}
      FORCE_SIDE: ${{ inputs.force_side }}
      CRYPTO_AUTOPICK: ${{ inputs.crypto_autopick }}
      EQUITY_AUTOPICK: ${{ inputs.equity_autopick }}
      AUTOPICK_OVERRIDES: ${{ inputs.advanced_json }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        run: |
          echo "CONFIG:"
          echo "  dry_run=$DRY_RUN"
          echo "  symbols=$SYMBOLS"
          echo "  start=$START end=$END"
          echo "  crypto_autopick=$CRYPTO_AUTOPICK equity_autopick=$EQUITY_AUTOPICK"
          echo "  force_side=$FORCE_SIDE"
          python main.py

      - name: List out/
        run: |
          echo "Listing out/:"
          ls -la out || true

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: trade-outputs.zip
          path: out/
          if-no-files-found: warn
