name: headless-trader-live

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry-run mode? true/false"
        required: true
        default: "true"
      symbols:
        description: "Comma-separated symbols (leave blank or a single space for autopick)"
        required: true
        default: "SPY,BTC-USD"
      equity_dollars_per_trade:
        description: "EQUITY dollars per trade"
        required: true
        default: "200"
      crypto_dollars_per_trade:
        description: "CRYPTO dollars per trade"
        required: true
        default: "5"
      force_side:
        description: "Force side for crypto (buy/sell or empty)"
        required: false
        default: ""
      crypto_autopick:
        description: "Autopick crypto top movers? true/false"
        required: true
        default: "true"
      equity_autopick:
        description: "Autopick equities top movers? true/false"
        required: true
        default: "false"
      daily_equity_cap:
        description: "Max EQUITY spend per day (USD)"
        required: true
        default: "25"
      daily_crypto_cap:
        description: "Max CRYPTO spend per day (USD)"
        required: true
        default: "15"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          DRY_RUN: ${{ github.event.inputs.dry_run }}
          SYMBOLS: ${{ github.event.inputs.symbols }}
          # START/END intentionally omitted to keep inputs under the 10-limit.
          # main.py will handle blanks (defaults).
          START: ""
          END: ""
          EQUITY_DOLLARS_PER_TRADE: ${{ github.event.inputs.equity_dollars_per_trade }}
          CRYPTO_DOLLARS_PER_TRADE: ${{ github.event.inputs.crypto_dollars_per_trade }}
          FORCE_SIDE: ${{ github.event.inputs.force_side }}
          CRYPTO_AUTOPICK: ${{ github.event.inputs.crypto_autopick }}
          EQUITY_AUTOPICK: ${{ github.event.inputs.equity_autopick }}
          # Advanced inputs pared back to stay under the limit
          AUTOPICK_OVERRIDES: ""
          OUT_DIR: "out"
          # Brokers / Exchanges
          EQUITY_BROKER: robinhood
          CRYPTO_EXCHANGE: kraken
          # API/Secret envs are expected to be set as repo secrets in Actions settings
          RH_USERNAME: ${{ secrets.RH_USERNAME }}
          RH_PASSWORD: ${{ secrets.RH_PASSWORD }}
          RH_TOTP_SECRET: ${{ secrets.RH_TOTP_SECRET }}
          CRYPTO_API_KEY: ${{ secrets.CRYPTO_API_KEY }}
          CRYPTO_API_SECRET: ${{ secrets.CRYPTO_API_SECRET }}
          CRYPTO_API_PASSPHRASE: ${{ secrets.CRYPTO_API_PASSPHRASE }}
          # Daily spend caps (new)
          DAILY_EQUITY_CAP: ${{ github.event.inputs.daily_equity_cap }}
          DAILY_CRYPTO_CAP: ${{ github.event.inputs.daily_crypto_cap }}
        run: |
          echo "CONFIG:"
          echo "  dry_run=$DRY_RUN"
          echo "  symbols=$SYMBOLS"
          echo "  start=$START end=$END"
          echo "  crypto_autopick=$CRYPTO_AUTOPICK equity_autopick=$EQUITY_AUTOPICK"
          echo "  force_side=$FORCE_SIDE"
          python main.py

      - name: List out/
        run: |
          echo "Listing out/:"
          ls -la out || true

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: trade-outputs.zip
          path: out/
          if-no-files-found: warn
