name: headless-trader

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry-run mode? (true/false)"
        required: true
        default: "true"
      symbols:
        description: "Comma-separated symbols"
        required: true
        default: "AAPL,MSFT,BTC-USD"
      start:
        description: "Start date (YYYY-MM-DD)"
        required: true
        default: "2023-01-01"
      end:
        description: "End date (YYYY-MM-DD, empty = today)"
        required: false
        default: ""
      equity_dollars:
        description: "EQUITY dollars per trade (override)"
        required: false
        default: "200"
      crypto_dollars:
        description: "CRYPTO dollars per trade (override)"
        required: false
        default: "100"
  schedule:
    # ~09:35 AM ET on weekdays (13:35 UTC during DST)
    - cron: "35 13 * * 1-5"
    # ~03:50 PM ET on weekdays (19:50 UTC during DST)
    - cron: "50 19 * * 1-5"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run trader (main.py)
        env:
          # Inputs (with safe defaults so schedule runs work too)
          SYMBOLS: ${{ github.event.inputs.symbols || 'AAPL,MSFT,BTC-USD' }}
          START:   ${{ github.event.inputs.start   || '2023-01-01' }}
          END:     ${{ github.event.inputs.end     || '' }}
          DRY_RUN: ${{ github.event.inputs.dry_run || 'true' }}

          # Optional per-trade dollar overrides
          EQUITY_DOLLARS_PER_TRADE:  ${{ github.event.inputs.equity_dollars || '200' }}
          CRYPTO_DOLLARS_PER_TRADE:  ${{ github.event.inputs.crypto_dollars || '100' }}

          OUT_DIR: out

          # Brokers (safe if unset)
          EQUITY_BROKER: robinhood
          RH_USERNAME:      ${{ secrets.RH_USERNAME }}
          RH_PASSWORD:      ${{ secrets.RH_PASSWORD }}
          RH_TOTP_SECRET:   ${{ secrets.RH_TOTP_SECRET }}   # optional
          RH_DEVICE_TOKEN:  ${{ secrets.RH_DEVICE_TOKEN }}  # optional

          CRYPTO_EXCHANGE:        ${{ vars.CRYPTO_EXCHANGE }}
          CRYPTO_API_KEY:         ${{ secrets.CRYPTO_API_KEY }}
          CRYPTO_API_SECRET:      ${{ secrets.CRYPTO_API_SECRET }}
          CRYPTO_API_PASSPHRASE:  ${{ secrets.CRYPTO_API_PASSPHRASE }}
        run: python main.py

      - name: List outputs (for diagnostics)
        run: |
          echo "Listing out/:"
          ls -lah out || true

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: trade-outputs
          path: out/**
          if-no-files-found: warn
