name: headless-trader [RETIRED]

on:
  workflow_dispatch:   # manual only — no schedule

concurrency:
  group: headless-trader-retired
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"
  DRY_RUN: "true"      # belt & suspenders so it can’t trade if clicked

jobs:
  noop:
    name: Retired workflow
    runs-on: ubuntu-latest
    steps:
      - name: Show message
        run: |
          echo "This workflow is retired. Use '.github/workflows/crypto-live.yml' for the live bot."
