name: Trader Live

on:
  workflow_dispatch:
  schedule:
    # Morning + evening (UTC). 14:00 UTC ≈ 7 AM PT / 10 AM ET; 22:00 UTC ≈ 3 PM PT / 6 PM ET
    - cron: "0 14 * * *"
    - cron: "0 22 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    # Prevent overlapping equity runs
    concurrency:
      group: equities-live
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Trader Live (equities, cautious caps)
        env:
          # Force LIVE
          TRADE_MODE: "live"
          DRY_RUN: "false"

          # Notifications
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

          # Robinhood creds
          ROBINHOOD_USERNAME: ${{ secrets.ROBINHOOD_USERNAME }}
          ROBINHOOD_PASSWORD: ${{ secrets.ROBINHOOD_PASSWORD }}
          ROBINHOOD_MFA:      ${{ secrets.ROBINHOOD_MFA }}
          RH_DEVICE_TOKEN:    ${{ secrets.RH_DEVICE_TOKEN }}
        run: |
          python main.py \
            --strategy cautious \
            --cap_per_trade 25 \
            --cap_daily 25 \
            --dry_run false
