name: headless-trader

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry-run mode? (true/false)"
        required: true
        default: "true"
      symbols:
        description: "Comma-separated symbols"
        required: true
        default: "BTC-USD"
      start:
        description: "Start date (YYYY-MM-DD)"
        required: true
        default: "2023-01-01"
      end:
        description: "End date (YYYY-MM-DD, empty=today)"
        required: false
        default: ""
      equity_dollars:
        description: "EQUITY dollars per trade (override)"
        required: false
        default: "200"
      crypto_dollars:
        description: "CRYPTO dollars per trade (override)"
        required: false
        default: "100"
      force_side:
        description: "Force side for crypto (buy/sell or empty)"
        required: false
        default: ""

      # ---------- Crypto autopick ----------
      crypto_autopick:
        description: "Auto-pick top crypto (true/false)"
        required: false
        default: "false"
      crypto_pick_n:
        description: "When crypto_autopick=true: number of tickers to add"
        required: false
        default: "3"
      crypto_min_usd:
        description: "When crypto_autopick=true: min 24h $ volume"
        required: false
        default: "500000"
      crypto_rank_by:
        description: "When crypto_autopick=true: rank by 'pct' (1d %) or 'vol'"
        required: false
        default: "pct"

      # ---------- Equities autopick ----------
      equity_autopick:
        description: "Auto-pick top equities from a liquid US universe (true/false)"
        required: false
        default: "false"
      equity_pick_n:
        description: "When equity_autopick=true: number of tickers to add"
        required: false
        default: "3"
      equity_min_dollar_vol:
        description: "When equity_autopick=true: min 5d avg $ volume (Close*Vol)"
        required: false
        default: "100000000"
      equity_rank_by:
        description: "When equity_autopick=true: rank by 'pct' (1d %) or 'vol'"
        required: false
        default: "pct"

  # Optional daily schedule (09:35 ET on weekdays)
  schedule:
    - cron: "35 13 * * 1-5"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          # Core inputs
          DRY_RUN: ${{ inputs.dry_run }}
          SYMBOLS: ${{ inputs.symbols }}
          START: ${{ inputs.start }}
          END: ${{ inputs.end }}
          EQUITY_DOLLARS_PER_TRADE: ${{ inputs.equity_dollars }}
          CRYPTO_DOLLARS_PER_TRADE: ${{ inputs.crypto_dollars }}
          FORCE_SIDE: ${{ inputs.force_side }}

          # Crypto autopick env
          CRYPTO_AUTOPICK: ${{ inputs.crypto_autopick }}
          CRY
